name: CI Pipeline

on:
  push:
    branches: [ main, dev ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Build
        run: echo "Build executado com sucesso"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Executar testes
        run: pytest --junitxml=resultado-testes.xml

      - name: Upload artifact de testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: resultado-testes.xml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso"